spring:
  data:
    mongodb:
      uri: mongodb+srv://pardipUser1:Pardip123@cluster0.9h6tkaz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal